
package mx.com.biblioteca.igu;

import javax.swing.filechooser.FileNameExtensionFilter;
import mx.com.biblioteca.logica.ControladoraLogica;

/**
 *
 * @author Raquel Martínez
 */
public class AgregarLibro extends javax.swing.JFrame {

    ControladoraLogica controladoraLogica;
    /**
     * Creates new form AgregarLibro
     */
    public AgregarLibro() {
        controladoraLogica = new ControladoraLogica();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooserPortadaLibro = new javax.swing.JFileChooser();
        panelAgregarLibro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTituloLibro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAutorLibro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEditorialLibro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEjemplaresDisponiblesLibros = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bttSeleccionarPortadaLibro = new javax.swing.JButton();
        txtRutaPortadaLibro = new javax.swing.JTextField();
        bttGuardarAgregarLibro = new javax.swing.JButton();
        bttLimpiarAgregarLibro = new javax.swing.JButton();

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png", "gif");
        chooserPortadaLibro.setFileFilter(filtro);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelAgregarLibro.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        jLabel1.setText("Agregar Libro");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setText("Título:");

        txtTituloLibro.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel3.setText("Autor:");

        txtAutorLibro.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel4.setText("Editorial:");

        txtEditorialLibro.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel5.setText("Portada:");

        txtEjemplaresDisponiblesLibros.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel6.setText("Ejemplares disponibles:");

        bttSeleccionarPortadaLibro.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        bttSeleccionarPortadaLibro.setText("Seleccionar");
        bttSeleccionarPortadaLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSeleccionarPortadaLibroActionPerformed(evt);
            }
        });

        txtRutaPortadaLibro.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        bttGuardarAgregarLibro.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        bttGuardarAgregarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton-Guardar.png"))); // NOI18N
        bttGuardarAgregarLibro.setText("  Guardar");
        bttGuardarAgregarLibro.setPreferredSize(new java.awt.Dimension(114, 40));
        bttGuardarAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGuardarAgregarLibroActionPerformed(evt);
            }
        });

        bttLimpiarAgregarLibro.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        bttLimpiarAgregarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton-Limpiar.png"))); // NOI18N
        bttLimpiarAgregarLibro.setText("Limpiar");
        bttLimpiarAgregarLibro.setPreferredSize(new java.awt.Dimension(114, 40));
        bttLimpiarAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLimpiarAgregarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarLibroLayout = new javax.swing.GroupLayout(panelAgregarLibro);
        panelAgregarLibro.setLayout(panelAgregarLibroLayout);
        panelAgregarLibroLayout.setHorizontalGroup(
            panelAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLibroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelAgregarLibroLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtEjemplaresDisponiblesLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelAgregarLibroLayout.createSequentialGroup()
                            .addComponent(bttGuardarAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bttLimpiarAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarLibroLayout.createSequentialGroup()
                            .addGroup(panelAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(25, 25, 25)
                            .addGroup(panelAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelAgregarLibroLayout.createSequentialGroup()
                                    .addComponent(bttSeleccionarPortadaLibro)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtRutaPortadaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtTituloLibro)
                                .addComponent(txtAutorLibro)
                                .addComponent(txtEditorialLibro)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelAgregarLibroLayout.setVerticalGroup(
            panelAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLibroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEditorialLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bttSeleccionarPortadaLibro)
                    .addComponent(txtRutaPortadaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEjemplaresDisponiblesLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttGuardarAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttLimpiarAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttSeleccionarPortadaLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSeleccionarPortadaLibroActionPerformed
        // Muestra la ventaja del buscador de archivos
        int resultado = chooserPortadaLibro.showOpenDialog(AgregarLibro.this);
        
        // Verifica si el usuario seleccionó un archivo
        if (resultado == chooserPortadaLibro.APPROVE_OPTION) {
            // Obtiene y actualiza la ruta de la portada seleccionada
            String portadaSeleccionadaPath = chooserPortadaLibro.getSelectedFile().getAbsolutePath();
            txtRutaPortadaLibro.setText(portadaSeleccionadaPath);
        }
        
    }//GEN-LAST:event_bttSeleccionarPortadaLibroActionPerformed

    private void bttGuardarAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGuardarAgregarLibroActionPerformed
        // Recupera los datos ingresados en el formulario
        String titulo = txtTituloLibro.getText();
        String autor = txtAutorLibro.getText();
        String editorial = txtEditorialLibro.getText();
        String rutaPortada = txtRutaPortadaLibro.getText();
        String ejemplaresDisponibles = txtEjemplaresDisponiblesLibros.getText();
        
        // Envía los datos del formulario a la lógica
        controladoraLogica.guardarLibro(titulo, autor, editorial, rutaPortada, ejemplaresDisponibles);
        
        // Limpia el formulario despues de guardarlos en la BD
        limpiarFormulario();
    }//GEN-LAST:event_bttGuardarAgregarLibroActionPerformed

    private void bttLimpiarAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLimpiarAgregarLibroActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_bttLimpiarAgregarLibroActionPerformed

    private void limpiarFormulario() {
        // Limpia el formulario 
        txtTituloLibro.setText("");
        txtAutorLibro.setText("");
        txtEditorialLibro.setText("");
        txtRutaPortadaLibro.setText("");
        txtEjemplaresDisponiblesLibros.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttGuardarAgregarLibro;
    private javax.swing.JButton bttLimpiarAgregarLibro;
    private javax.swing.JButton bttSeleccionarPortadaLibro;
    private javax.swing.JFileChooser chooserPortadaLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelAgregarLibro;
    private javax.swing.JTextField txtAutorLibro;
    private javax.swing.JTextField txtEditorialLibro;
    private javax.swing.JTextField txtEjemplaresDisponiblesLibros;
    private javax.swing.JTextField txtRutaPortadaLibro;
    private javax.swing.JTextField txtTituloLibro;
    // End of variables declaration//GEN-END:variables
}
